package org.changs.campus.domain;

public class Account {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column account.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column account.account
	 *
	 * @mbg.generated
	 */
	private String account;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column account.passwd
	 *
	 * @mbg.generated
	 */
	private String passwd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column account.userId
	 *
	 * @mbg.generated
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column account.id
	 *
	 * @return the value of account.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column account.id
	 *
	 * @param id
	 *            the value for account.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column account.account
	 *
	 * @return the value of account.account
	 *
	 * @mbg.generated
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column account.account
	 *
	 * @param account
	 *            the value for account.account
	 *
	 * @mbg.generated
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column account.passwd
	 *
	 * @return the value of account.passwd
	 *
	 * @mbg.generated
	 */
	public String getPasswd() {
		return passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column account.passwd
	 *
	 * @param passwd
	 *            the value for account.passwd
	 *
	 * @mbg.generated
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column account.userId
	 *
	 * @return the value of account.userId
	 *
	 * @mbg.generated
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column account.userId
	 *
	 * @param userid
	 *            the value for account.userId
	 *
	 * @mbg.generated
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
}